{{/* Generated by hack/sync-helm-manifests.sh from the +kubebuilder:rbac markers. Do not edit. */}}
{{- define "data-lake-operator.managerRules" -}}
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - datalakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - datalakes/finalizers
  verbs:
  - update
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - datalakes/status
  verbs:
  - get
  - patch
  - update
{{- end }}
