#!/usr/bin/env bash
# Render controller-gen output into the Helm chart.
#
# Two chart templates are generated from Go markers and must not be hand-edited:
#
#   config/crd/bases/*.yaml -> templates/crds.yaml
#   config/rbac/role.yaml   -> templates/_manager-rules.tpl
#
# CRDs live in templates/ rather than the chart's crds/ directory because Helm
# never upgrades or deletes anything in crds/, which would leave the cluster on
# a stale schema after `helm upgrade`. Templating them costs the built-in
# protection of crds/, so a resource-policy annotation is injected to keep the
# CRD (and therefore every custom resource it defines) on uninstall.
#
# The manager ClusterRole rules come from the +kubebuilder:rbac markers, so the
# chart includes them rather than duplicating them by hand. kustomize renders
# the same generated files independently; this script is what keeps the Helm
# chart in step with them.

set -euo pipefail

CRD_DIR="${1:-config/crd/bases}"
ROLE_FILE="${2:-config/rbac/role.yaml}"
CHART_DIR="${3:-deploy/data-lake-operator}"

TEMPLATES="${CHART_DIR}/templates"
mkdir -p "${TEMPLATES}"

# --- CRDs ---------------------------------------------------------------
shopt -s nullglob
crds=("${CRD_DIR}"/*.yaml)
if [ ${#crds[@]} -eq 0 ]; then
  echo "no CRDs found in ${CRD_DIR}; run 'make manifests' first" >&2
  exit 1
fi

{
  echo '{{- if .Values.crds.enabled -}}'
  echo '{{/* Generated by hack/sync-helm-manifests.sh. Do not edit. */}}'
  for f in "${crds[@]}"; do
    # Insert the keep policy into the top-level metadata.annotations block only,
    # which is the sole `annotations:` key at exactly two spaces of indent.
    awk '
      { print }
      /^  annotations:$/ && !seen {
        print "    {{- if $.Values.crds.keep }}"
        print "    \"helm.sh/resource-policy\": keep"
        print "    {{- end }}"
        seen = 1
      }
    ' "$f"
  done
  echo '{{- end }}'
} > "${TEMPLATES}/crds.yaml"

# --- Manager ClusterRole rules ------------------------------------------
if [ ! -f "${ROLE_FILE}" ]; then
  echo "no ${ROLE_FILE}; run 'make manifests' first" >&2
  exit 1
fi

# Take everything after the top-level `rules:` key. controller-gen emits the
# rules last, so the remainder of the file is the list we want.
rules="$(awk 'found { print } /^rules:$/ { found = 1 }' "${ROLE_FILE}")"
if [ -z "${rules}" ]; then
  echo "no rules found in ${ROLE_FILE}" >&2
  exit 1
fi

chart_name="$(awk '/^name:/{print $2; exit}' "${CHART_DIR}/Chart.yaml")"
if [ -z "${chart_name}" ]; then
  echo "no chart name in ${CHART_DIR}/Chart.yaml" >&2
  exit 1
fi

{
  echo '{{/* Generated by hack/sync-helm-manifests.sh from the +kubebuilder:rbac markers. Do not edit. */}}'
  echo "{{- define \"${chart_name}.managerRules\" -}}"
  printf '%s\n' "${rules}"
  echo '{{- end }}'
} > "${TEMPLATES}/_manager-rules.tpl"

echo "synced ${#crds[@]} CRD file(s) and manager RBAC rules into ${CHART_DIR}"
