{{/* Generated by hack/sync-helm-manifests.sh from the +kubebuilder:rbac markers. Do not edit. */}}
{{- define "data-analytics-operator.managerRules" -}}
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - analytics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - analytics/finalizers
  verbs:
  - update
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - analytics/status
  verbs:
  - get
  - patch
  - update
{{- end }}
